import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:google_mlkit_document_scanner/google_mlkit_document_scanner.dart';
import 'package:path_provider/path_provider.dart';
import 'package:image/image.dart' as img;

/// Service for document scanning with ML Kit edge detection and cropping
class DocumentScannerService {
  static DocumentScanner? _scanner;

  /// Initialize the ML Kit Document Scanner
  static DocumentScanner _getScanner() {
    if (_scanner != null) return _scanner!;

    _scanner = DocumentScanner(
      options: DocumentScannerOptions(
        pageLimit: 10,
        isGalleryImport: true,
      ),
    );
    return _scanner!;
  }

  /// Scan document using ML Kit's built-in scanner with edge detection and cropping
  /// Returns list of cropped and processed image paths
  static Future<List<String>> scanDocumentWithMLKit() async {
    try {
      final scanner = _getScanner();
      final DocumentScanningResult result = await scanner.scanDocument();

      if (result.pdf != null) {
        debugPrint('DocumentScannerService: PDF generated by ML Kit');
      }

      final List<String> processedPaths = [];
      
      // Get images from scan result
      if (result.images != null && result.images!.isNotEmpty) {
        for (var imagePath in result.images!) {
          // Images are already cropped and enhanced by ML Kit
          processedPaths.add(imagePath);
        }
      }

      return processedPaths;
    } catch (e) {
      debugPrint('DocumentScannerService: ML Kit scan failed: $e');
      return [];
    }
  }

  /// Process a single image file with ML Kit edge detection and perspective correction
  /// Uses ML Kit Document Scanner for automatic cropping
  static Future<String?> processImageWithEdgeDetection(String inputPath) async {
    try {
      final File inputFile = File(inputPath);
      if (!await inputFile.exists()) {
        debugPrint('DocumentScannerService: Input file does not exist');
        return null;
      }

      // Read the image
      final Uint8List imageBytes = await inputFile.readAsBytes();
      final img.Image? originalImage = img.decodeImage(imageBytes);

      if (originalImage == null) {
        debugPrint('DocumentScannerService: Failed to decode image');
        return inputPath; // Return original if processing fails
      }

      // Try edge detection with lower threshold for better results
      img.Image processed = originalImage.clone();
      bool didCrop = false;
      
      try {
        // Detect edges using Sobel operator with moderate settings
        final img.Image grayscale = img.grayscale(originalImage);
        
        // Apply slight blur to reduce noise before edge detection
        final blurred = img.gaussianBlur(grayscale, radius: 2);
        final img.Image edges = img.sobel(blurred);
        
        // Try to find document boundaries
        final corners = _findDocumentCorners(edges, originalImage);
        
        if (corners != null && corners.length == 4) {
          // Crop to detected document boundaries
          processed = _cropToCorners(originalImage, corners);
          didCrop = true;
          debugPrint('DocumentScannerService: Document edges detected and cropped');
        } else {
          debugPrint('DocumentScannerService: No clear document edges found, using full image');
        }
      } catch (e) {
        debugPrint('DocumentScannerService: Edge detection failed: $e, using full image');
        processed = originalImage.clone();
      }

      // Apply enhancement to the processed image
      final img.Image enhanced = _enhanceDocument(processed);

      // Save processed image
      final Directory tempDir = await getTemporaryDirectory();
      final String outputPath = '${tempDir.path}/processed_${DateTime.now().millisecondsSinceEpoch}.jpg';
      final File outputFile = File(outputPath);
      
      await outputFile.writeAsBytes(img.encodeJpg(enhanced, quality: 95));

      debugPrint('DocumentScannerService: Image processed and saved to $outputPath (cropped: $didCrop)');
      return outputPath;
    } catch (e) {
      debugPrint('DocumentScannerService: Image processing failed: $e');
      return inputPath; // Return original on error
    }
  }

  /// Find document corners using edge detection
  static List<img.Point>? _findDocumentCorners(img.Image edges, img.Image original) {
    try {
      // Find the brightest pixels (edges) - use lower threshold
      final List<img.Point> edgePoints = [];
      
      // Scan the image and collect strong edge points
      for (int y = 0; y < edges.height; y += 3) { // Sample every 3 pixels for speed
        for (int x = 0; x < edges.width; x += 3) {
          final pixel = edges.getPixel(x, y);
          // In grayscale images, the pixel value itself represents brightness
          final brightness = pixel.r.toInt(); // Get red channel (R=G=B for grayscale)
          
          // Lower threshold for better detection
          if (brightness > 80) { // Increased from 60 for clearer edges
            edgePoints.add(img.Point(x, y));
          }
        }
      }

      if (edgePoints.length < 100) {
        debugPrint('DocumentScannerService: Not enough edge points found (${edgePoints.length})');
        return null;
      }

      debugPrint('DocumentScannerService: Found ${edgePoints.length} edge points');

      // Find approximate corners using convex hull approach
      img.Point? topLeft, topRight, bottomLeft, bottomRight;
      double minSumXY = double.infinity;
      double maxSumXY = double.negativeInfinity;
      double minDiffXY = double.infinity;
      double maxDiffXY = double.negativeInfinity;

      for (var point in edgePoints) {
        final sum = (point.x + point.y).toDouble();
        final diff = (point.x - point.y).toDouble();

        if (sum < minSumXY) {
          minSumXY = sum;
          topLeft = point;
        }
        if (sum > maxSumXY) {
          maxSumXY = sum;
          bottomRight = point;
        }
        if (diff < minDiffXY) {
          minDiffXY = diff;
          bottomLeft = point;
        }
        if (diff > maxDiffXY) {
          maxDiffXY = diff;
          topRight = point;
        }
      }

      if (topLeft != null && topRight != null && bottomLeft != null && bottomRight != null) {
        // Validate that we have a reasonable quadrilateral
        final width = original.width;
        final height = original.height;
        
        // Check if corners are reasonably far apart (at least 30% of image dimensions)
        final minWidth = width * 0.3;
        final minHeight = height * 0.3;
        
        final detectedWidth = (topRight.x - topLeft.x).abs().toDouble();
        final detectedHeight = (bottomLeft.y - topLeft.y).abs().toDouble();
        
        debugPrint('DocumentScannerService: Detected size: ${detectedWidth}x$detectedHeight, Min: ${minWidth}x$minHeight');
        debugPrint('DocumentScannerService: Corners - TL:(${topLeft.x},${topLeft.y}) TR:(${topRight.x},${topRight.y}) BR:(${bottomRight.x},${bottomRight.y}) BL:(${bottomLeft.x},${bottomLeft.y})');
        
        if (detectedWidth > minWidth && detectedHeight > minHeight) {
          return [topLeft, topRight, bottomRight, bottomLeft];
        } else {
          debugPrint('DocumentScannerService: Detected area too small');
        }
      }

      return null;
    } catch (e) {
      debugPrint('DocumentScannerService: Corner detection failed: $e');
      return null;
    }
  }

  /// Crop image to detected corners (simple bounding box crop)
  static img.Image _cropToCorners(img.Image source, List<img.Point> corners) {
    try {
      // Get corner coordinates
      final topLeft = corners[0];
      final topRight = corners[1];
      final bottomRight = corners[2];
      final bottomLeft = corners[3];

      // Find bounding box
      int minX = [topLeft.x, topRight.x, bottomRight.x, bottomLeft.x]
          .map((v) => v.toInt())
          .reduce((a, b) => a < b ? a : b);
      int maxX = [topLeft.x, topRight.x, bottomRight.x, bottomLeft.x]
          .map((v) => v.toInt())
          .reduce((a, b) => a > b ? a : b);
      int minY = [topLeft.y, topRight.y, bottomRight.y, bottomLeft.y]
          .map((v) => v.toInt())
          .reduce((a, b) => a < b ? a : b);
      int maxY = [topLeft.y, topRight.y, bottomRight.y, bottomLeft.y]
          .map((v) => v.toInt())
          .reduce((a, b) => a > b ? a : b);

      // Add small padding to avoid cutting edges
      minX = (minX - 10).clamp(0, source.width - 1);
      maxX = (maxX + 10).clamp(0, source.width);
      minY = (minY - 10).clamp(0, source.height - 1);
      maxY = (maxY + 10).clamp(0, source.height);

      final cropWidth = (maxX - minX).clamp(1, source.width - minX);
      final cropHeight = (maxY - minY).clamp(1, source.height - minY);

      debugPrint('DocumentScannerService: Cropping from ($minX, $minY) size: ${cropWidth}x$cropHeight');

      // Crop to bounding box
      final cropped = img.copyCrop(
        source,
        x: minX,
        y: minY,
        width: cropWidth,
        height: cropHeight,
      );

      return cropped;
    } catch (e) {
      debugPrint('DocumentScannerService: Crop failed: $e');
      return source; // Return original if cropping fails
    }
  }

  /// Enhance document image (brightness, contrast, sharpness)
  static img.Image _enhanceDocument(img.Image image) {
    try {
      // Clone the image to avoid modifying original
      img.Image enhanced = image.clone();

      // Very subtle enhancement to avoid inversion (minimal adjustment)
      enhanced = img.adjustColor(
        enhanced,
        contrast: 1.05, // Very light contrast boost
        brightness: 1.0, // No brightness change
        saturation: 1.0, // Keep original saturation
      );

      // Skip sharpening to avoid artifacts that could cause inversion
      // The light contrast boost is sufficient for most documents

      return enhanced;
    } catch (e) {
      debugPrint('DocumentScannerService: Enhancement failed, returning original: $e');
      return image; // Return original if enhancement fails
    }
  }

  /// Detect document edges in an image (simplified algorithm)
  /// Returns corner points if detected, null otherwise
  static Future<List<img.Point>?> detectDocumentEdges(String imagePath) async {
    try {
      debugPrint('DocumentScannerService: Starting edge detection for: $imagePath');
      
      final File file = File(imagePath);
      if (!await file.exists()) {
        debugPrint('DocumentScannerService: File does not exist');
        return null;
      }

      final Uint8List imageBytes = await file.readAsBytes();
      final img.Image? image = img.decodeImage(imageBytes);

      if (image == null) {
        debugPrint('DocumentScannerService: Failed to decode image');
        return null;
      }

      debugPrint('DocumentScannerService: Image loaded: ${image.width}x${image.height}');

      // Convert to grayscale
      final img.Image grayscale = img.grayscale(image);

      // Apply edge detection with preprocessing
      final blurred = img.gaussianBlur(grayscale, radius: 3);
      final img.Image edges = img.sobel(blurred);

      debugPrint('DocumentScannerService: Edge detection complete');

      // Find document corners
      final corners = _findDocumentCorners(edges, image);

      if (corners != null) {
        debugPrint('DocumentScannerService: Successfully detected ${corners.length} corners');
      } else {
        debugPrint('DocumentScannerService: No clear document boundaries found');
      }

      return corners;
    } catch (e) {
      debugPrint('DocumentScannerService: Edge detection failed: $e');
      return null;
    }
  }

  /// Clean up scanner resources
  static void dispose() {
    _scanner?.close();
    _scanner = null;
  }
}
